### ISSUE TITLE
feature: daily currency rate updates

### ISSUE THREAD

**Issue by connecticus** [itbeaver/spree_fx_currency#26]
It will be great to have ability update rates automatically.

**Comment by artem-russkikh** [comment]
I think it would be better to add information about how to do that in README or Wiki

@misteral what do you think?

There is a need for cron or rufus-scheduler that, in my opinion, better should be realized outside of the gem

**Comment by misteral** [comment]
@artem-russkikh yes I am agree with you.

**Comment by artem-russkikh** [comment]
@connecticus i added 'how-to' to the wiki https://github.com/itbeaver/spree_fx_currency/wiki/How-to-automatically-update-currencies-everyday

**Comment by connecticus** [comment]
Thank you Artem I am really appreciate your help.
