### ISSUE TITLE
Master branch

### ISSUE THREAD

**Issue by artem-russkikh** [itbeaver/spree_fx_currency#5]
Implement for master branch

**Comment by misteral** [comment]
I think in current situation, master = current dev branch, 3-0-stable for stable releases

**Comment by artem-russkikh** [comment]
@misteral yes, it should be like spree repo, now master have only blank extension

**Comment by misteral** [comment]
@artem-russkikh Please merge with 3-0-stable

**Comment by artem-russkikh** [comment]
Master now contain last code
