### ISSUE TITLE
3-1-stable branch

### ISSUE THREAD

**Issue by artem-russkikh** [itbeaver/spree_fx_currency#6]
Implement for 3-1-stable branch

**Comment by vkdimitrov** [comment]
Something new here?

**Comment by artem-russkikh** [comment]
@vkdimitrov i can check it with 3-1-stable tomorrow

**Comment by artem-russkikh** [comment]
@vkdimitrov it's looks good, but there is may be issue with spree_multi_currency gem
https://github.com/spree-contrib/spree_multi_currency/issues/64

Thank you for PR! I've merged it into master and pushed 3-1-stable branch
